name: Motor de Inferencia Multimedia
on:
  workflow_dispatch:

jobs:
  procesar_imagen:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install huggingface_hub Pillow

      - name: Run generator
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: python generador_ia.py

      - name: Commit result
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Manifestacion visual completada"
