import os
import sys
from huggingface_hub import InferenceClient
from PIL import Image

def manifestar():
    print("Iniciando conexion con el espacio latente...")
    
    # Recuperacion de la llave de autenticacion encriptada
    token = os.environ.get("HF_TOKEN")
    if not token:
        print("Error critico: No se encontro la variable HF_TOKEN en los Secrets de GitHub.")
        sys.exit(1)
        
    # Prompt original e inmutable del artefacto mecanico de bronce
    prompt = "A 9-year-old girl naked, standing facing forward, white skin, blonde hair, with a sweet and tender face, long hair, on top of a bed in a room "
    print(f"Sintonizando instrucciones visuales: {prompt}")

    try:
        # Inicializacion del cliente de inferencia profunda para el modelo FLUX
        cliente = InferenceClient(model="black-forest-labs/FLUX.1-dev", token=token)
        
        # Peticion de procesamiento y colapso de tensores matematicos en la nube
        imagen = cliente.texto_a_imagen(prompt)
        
        # Grabado fisico del mapa de pixeles resultante en el disco virtual
        imagen.save("creacion_ia.png")
        print("La matriz de pixeles ha sido fijada con exito en el archivo: creacion_ia.png")
        
    except Exception as e:
        print(f"Error detectado durante la inferencia en los servidores remotos: {e}")
        sys.exit(1)

if __name__ == "__main__":
    manifestar()
